#!/bin/bash
#$ -N table1_yl
#$ -cwd
#$ -o analysis/table1/output/table1_job.out
#$ -e analysis/table1/output/table1_job.err
#$ -l h_rt=00:30:00
#$ -l mem=8G
#$ -pe smp 1

module purge
module load tools/prod
module load R/4.3.2-gfbf-2023a

cd /rds/general/project/hda_25-26/live/TDS/TDS_Group1

Rscript analysis/table1/table1_run.R